# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TxFUX8Zj86ntENMJr9CQdSOfpd3wlcX_
"""

import pandas as pd
import numpy as np
import random

stock = pd.read_csv('./sample_data/stock_data.csv', encoding='cp949')

stock.head()

stock['단축코드']

stock.iloc[0,[1, 3]]

print(stock.iloc[1,[1, 3]])

print(stock.iloc[1, 1])
print(stock.iloc[1, 3])

print(f'("{stock.iloc[1, 1]}", "{stock.iloc[1, 3]}"),')

for row_index in range(stock.shape[0]):
  print(f'("{stock.iloc[row_index, 1]}", "{stock.iloc[row_index, 3]}"),')

max_len = 0
for row_index in range(stock.shape[0]):
  max_len = max(max_len, len(stock.iloc[row_index, 3]))
print(max_len)

for row_index in range(stock.shape[0]):
  print(f'\tticker_map.insert(std::make_pair<std::string, int>("{stock.iloc[row_index, 1]}", {row_index}));')

import random

# for row_index in range(stock.shape[0]):

for second in range(0, 60, 5):
  print(f"(", end="")
  print(f'"2023-08-06 00:00:{second}"', end=", ")
  ticker_index_list = []
  for _ in range(10):
    ticker_index = random.randint(0, 20)
    while ticker_index in ticker_index_list:
      ticker_index = random.randint(0, 20)
    ticker_index_list.append(ticker_index)

  for ticker_index in ticker_index_list[:-1]:
    print(f'"{stock.iloc[ticker_index, 1]}"',end =", ")
  print(f'"{stock.iloc[ticker_index, 1]}"),')

for row_index in range(stock.shape[0]-2730):
  print(f'\tput("{stock.iloc[row_index, 1]}", "{stock.iloc[row_index, 3]}", {row_index}));')

# for row_index in range(stock.shape[0]):

prev1, prev2 = 0, 0
acc1, acc2 = 0, 0

for hour in range(8, 10):
  for minute in range(60):

    for second in range(2, 60, 5):
      print(f"(", end="")
      print(f'"2023-08-06 {hour}:{minute}:{second}"', end=", ")
      prev1, prev2 = random.randint(1000, 2000), random.randint(1000, 2000)
      acc1 += prev1
      acc2 += prev2
      print(f'{acc1}, {acc2}',end ="")
      print(f'),')

for row_index in range(stock.shape[0]):
  print(f'ticker_{stock.iloc[row_index, 1]}\tINT,')













