-- 2022년 10월에 작성된
--게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을
-- 결과는 댓글 작성일을 기준으로 오름차순 정렬해주시고, 게시글 제목을 기준으로 오름차순 정렬해주세요.
SELECT BOARD.TITLE,
        REPLY.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID,
        REPLY.CONTENTS, TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_BOARD BOARD
    INNER JOIN USED_GOODS_REPLY REPLY
        ON TO_CHAR(BOARD.CREATED_DATE, 'YYYY-MM') = '2022-10'
        AND BOARD.BOARD_ID = REPLY.BOARD_ID
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE