-- 코드를 입력하세요

-- PATIENT
-- PT_NO, PT_NAME, GEND_CD, AGE, TLNO


-- DOCTOR
-- DR_NAME, DR_ID, LCNS_NO, HIRE_YMD, MCDP_CD(진료 과 코드)) TLNO

-- APPINTMENt (예약목록)
-- APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID(진료 의사 id), APNT_CNCL_YN, APNT_CNCL_YMN


-- 2022 -4 13 취소되지 않은 흉부외과(CS) 진료 예약 내역
-- ORDER BY 진료 예약 일시 ASC

# SELECT APNT_YMD, DATE(APNT_YMD)
# FROM APPOINTMENT;
# WHERE APNT_YMD BETWEEN '2022-04-13 00:00:00' and '2022-04-13 23:59:59'

SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
    LEFT OUTER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    LEFT OUTER JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE
    A.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
    AND A.MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC    